from pathlib import Path
import xml.etree.ElementTree as ET


ROOT = Path(__file__).resolve().parents[1]
TS = ROOT / "assets" / "translations" / "asrtu_en.ts"

TRANSLATIONS = {
    "CRC未通过": "CRC failed",
    "已接收 %1 / %2 包　·　CRC未通过 %3 包　·　缺失 %4 包　·　完整率 %5%": "Received %1 / %2  ·  CRC failed %3  ·  Missing %4  ·  Integrity %5%",
    "已接收 %1 包　·　CRC未通过 %2 包　·　确认缺失 %3 包　·　最新包序号 %4　·　总包数待确定": "Received %1  ·  CRC failed %2  ·  Confirmed missing %3  ·  Latest packet %4  ·  Total pending EOI",
    "无法按当前模式打开音频输入设备。\n\n“立体声零中频 RAW 模式 I/Q 输入”必须由声卡提供两个录音声道；若你的电台或麦克风只有一个声道，请在启动器中选择“单声道实数域 12KHz 电台 IF 输入”。\n\n底层错误：%1": "Unable to open the audio input device in the current mode.\n\n‘Stereo Zero-IF RAW I/Q Input’ requires two recording channels. If your radio or microphone has only one channel, select ‘Mono Real 12 kHz Radio IF Input’ in the launcher.\n\nUnderlying error: %1",
    "SatNOGS 上传程序启动后立即退出（代码 %1）。": "The SatNOGS uploader exited immediately after launch (code %1).",
    "SatNOGS 上传程序启动失败": "Unable to Start SatNOGS Uploader",
    "SatNOGS 上传程序已启动：%1（PID %2）": "SatNOGS uploader started: %1 (PID %2)",
    "MMT 与 SatNOGS 上传均已启动（PID %1 / %2）": "MMT and SatNOGS uploaders started (PID %1 / %2)",
    "已保存 %1 设置（未启用 SatNOGS 上传）": "%1 settings saved (SatNOGS upload disabled)",
    "SatNOGS 上传配置无效": "Invalid SatNOGS Upload Configuration",
    "SatNOGS NORAD ID 无效。": "The SatNOGS NORAD ID is invalid.",
    "地面站呼号或昵称不能为空。": "The ground-station callsign or nickname cannot be empty.",
    "地面站经纬度超出有效范围。": "The ground-station coordinates are outside the valid range.",
    "ZMQ 地址必须使用 tcp://。": "The ZMQ address must use tcp://.",
    "SatNOGS API 地址无效。": "The SatNOGS API address is invalid.",
    "等待遥测帧…": "Waiting for telemetry frames…",
    "长度：%1 字节\n": "Length: %1 bytes\n",
    "ASRTU SatNOGS 遥测上传": "ASRTU SatNOGS Telemetry Uploader",
    "遥测帧内容": "Telemetry Frame Data",
    "站点与上传配置": "Station and Upload Configuration",
    "服务器反馈": "Server Feedback",
    "Configuration:\nZMQ Address:\n  %1\nSatNOGS API:\n  %2\nSatellite Name: %3\nNORAD ID: %4\nGround Station: %5\nLongitude: %6\nAltitude: %7 m\nLatitude: %8": "Configuration:\nZMQ Address:\n  %1\nSatNOGS API:\n  %2\nSatellite Name: %3\nNORAD ID: %4\nGround Station: %5\nLongitude: %6\nAltitude: %7 m\nLatitude: %8",
    "无法创建 ZeroMQ 上下文：%1": "Unable to create the ZeroMQ context: %1",
    "无法创建 ZeroMQ 订阅套接字：%1": "Unable to create the ZeroMQ subscriber socket: %1",
    "无法连接到 %1：%2": "Unable to connect to %1: %2",
    "已连接 ZeroMQ 订阅端，等待解码器帧。": "ZeroMQ subscriber connected; waiting for decoder frames.",
    "SatNOGS HTTPS 上传已就绪。": "SatNOGS HTTPS upload is ready.",
    "预览模式：已载入示例遥测帧。": "Preview mode: sample telemetry frame loaded.",
    "ZeroMQ 接收失败：%1": "ZeroMQ receive failed: %1",
    "已丢弃超长 ZeroMQ 消息（%1 字节）。": "Discarded an oversized ZeroMQ message (%1 bytes).",
    "已丢弃无效遥测 PDU：%1": "Discarded an invalid telemetry PDU: %1",
    "接收序号：%1\n接收时间：%2 UTC\n\n": "Sequence: %1\nReceived: %2 UTC\n\n",
    "上传队列已满，已丢弃最旧的一帧。": "The upload queue is full; the oldest frame was discarded.",
    "收到遥测帧 #%1（%2 字节），加入上传队列。": "Telemetry frame #%1 received (%2 bytes) and queued for upload.",
    "SatNOGS 接受 %1 字节帧（HTTP %2）。": "SatNOGS accepted the %1-byte frame (HTTP %2).",
    "SatNOGS 上传失败（HTTP %1）：%2": "SatNOGS upload failed (HTTP %1): %2",
    "服务器响应：%1": "Server response: %1",
    "SSDV图像接收": "SSDV Image Reception",
    "等待SSDV图像数据": "Waiting for SSDV image data",
    "复制图像": "Copy Image",
    "清除图像": "Clear Image",
    "保存路径：—": "Saved to: —",
    "保存路径：%1": "Saved to: %1",
    "图像ID：%1　分辨率：%2×%3　质量：%4\n数据包：%5（%6–%7，区间缺失%8）　状态：%9": "Image ID: %1   Resolution: %2×%3   Quality: %4\nPackets: %5 (%6–%7, %8 missing in range)   Status: %9",
    "完成": "Complete",
    "接收中": "Receiving",
    "打开目录": "Open Folder",
    "上一张图像": "Previous Image",
    "下一张图像": "Next Image",
    "已接收": "Received",
    "确认缺失": "Confirmed missing",
    "尚未确定": "Pending",
    "尚未接收到数据包": "No packets received yet",
    "%1 · SSDV 图像 %2": "%1 · SSDV Image %2",
    "分辨率 %1 × %2　·　质量 %3": "Resolution %1 × %2  ·  Quality %3",
    "已接收 %1 / %2 包　·　缺失 %3 包　·　完整率 %4%": "Received %1 / %2  ·  Missing %3  ·  Integrity %4%",
    "已接收 %1 包　·　确认缺失 %2 包　·　最新包序号 %3　·　总包数待确定": "Received %1  ·  Confirmed missing %2  ·  Latest packet %3  ·  Total pending EOI",
    "来源卫星：%1": "Source satellite: %1",
    "图像ID：%1　分辨率：%2×%3　质量：%4": "Image ID: %1   Resolution: %2×%3   Quality: %4",
    "数据包：0/0": "Packets: 0/0",
    "区间缺失 %1": "%1 missing in range",
    "数据包：%1/%2　区间缺失 %3": "Packets: %1/%2   missing in range: %3",
    "声卡切换失败": "Audio Device Switch Failed",
    "无法切换到所选声卡。请重新选择可用设备或重新启动接收。\n%1": "Unable to switch to the selected audio device. Select an available device or restart the receiver.\n%1",
    "当前声卡不可用。请在启动器中选择另一输入设备。\n%1": "The current audio device is unavailable. Select another input device in the launcher.\n%1",
    "I/Q 输入异常": "I/Q Input Mismatch",
    "检测到 I/Q 两路幅度严重不平衡，当前输入可能是单声道 USB/实数音频，因此频谱会出现镜像。\n请在启动器中改选“单声道实数域 12KHz 电台 IF 输入”。": "The I and Q channel levels are severely imbalanced. The input may be mono USB/real audio, which produces a mirrored spectrum.\nSelect ‘Mono Real 12 kHz Radio IF Input’ in the launcher.",
    "无法创建录音和日志目录：\n%1": "Unable to create the recording and log directory:\n%1",
    "找不到程序：\n%1": "Program not found:\n%1",
    "无法启动：\n%1": "Unable to start:\n%1",
    "尚未配置上传信息，请先保存设置。": "Upload information is not configured. Save the settings first.",
    "上传代理启动后立即退出（代码 %1）。": "The upload proxy exited immediately after launch (code %1).",
    "\n日志：%1": "\nLog: %1",
    "\n\n最后输出：\n%1": "\n\nLast output:\n%1",
    "找不到录音格式转换器。 ": "Audio format converter not found. ",
    "无法转换录音文件：/%1": "Unable to convert the recording: /%1",
    "仅支持单声道或双声道录音文件。": "Only mono or stereo recordings are supported.",
    "所选卫星没有可用的 SatNOGS NORAD ID。": "The selected satellite has no available SatNOGS NORAD ID.",
    "阿斯图系列卫星启动器": "ASRTU Series Satellite Launcher",
    "阿斯图系列卫星接收与遥测上传": "ASRTU Series Satellite Reception and Telemetry Upload",
    "配置接收输入与地面站资料，再按需启动各个组件。": "Configure the receiver input and ground-station details, then start each component as needed.",
    "接收与上传设置": "Reception and Upload Settings",
    "本地内存共享 RAW 模式 I/Q 桥接": "Local Shared-Memory RAW I/Q Bridge",
    "立体声零中频 RAW 模式 I/Q 输入": "Stereo Zero-IF RAW I/Q Input",
    "单声道实数域 12KHz 电台 IF 输入": "Mono Real 12 kHz Radio IF Input",
    "输入声道不匹配": "Input Channel Mismatch",
    "打开录音目录": "Open Recordings Folder",
    "快速重放录音": "Quick Replay Recording",
    "快速重放失败": "Quick Replay Failed",
    "多普勒工具启动失败": "Unable to Start Doppler Tool",
    "正在下载第 %1/%2 个 TLE 来源": "Downloading TLE source %1 of %2",
    "TLE 更新完成：%1/%2 个来源": "TLE update complete: %1 of %2 sources",
    "在线更新失败，继续使用本地 TLE 数据": "Online update failed; continuing with local TLE data",
    "尚未配置上传信息，请先填写呼号和地面站资料。": "Upload information is not configured. Enter the call sign and ground-station details first.",
    "当前模式需要双声道 I/Q，但所选声卡仅提供单声道。\n若输入来自电台 12 kHz 中频或 SDR# 的 USB 音频，请改选“单声道实数域 12KHz 电台 IF 输入”。": "This mode requires stereo I/Q, but the selected audio device provides only one channel.\nFor a radio 12 kHz IF or SDR# USB audio, select ‘Mono Real 12 kHz Radio IF Input’.",
    "自动保存本次接收录音": "Automatically save this reception recording",
    "同时上传至 SatNOGS": "Also upload to SatNOGS",
    "输入": "Input",
    "声卡": "Sound card",
    "呼号": "Callsign",
    "经度": "Longitude",
    "纬度": "Latitude",
    "海拔": "Altitude",
    "常用工具": "Tools",
    "打开 SDR# 遥测预设": "Open SDR# Telemetry Preset",
    "卫星跟踪与自动多普勒": "Satellite / Doppler Tracking",
    "播放录音文件": "Play Recording File",
    "快速播放录音文件": "Quick Play Recording File",
    "打开录音与日志": "Open Recordings and Logs",
    "就绪": "Ready",
    "保存设置": "Save Settings",
    "启动接收": "Start Receiver",
    "启动上传代理": "Start Upload Proxy",
    "启动上传": "Start Upload",
    "上传设置": "Upload Settings",
    "SDR# 启动失败": "Failed to Start SDR#",
    "无法打开目录": "Unable to Open Directory",
    "选择接收录音": "Select Reception Recording",
    "接收录音 (*.wav *.ogg *.oga *.opus *.flac *.mp3)": "Reception Recordings (*.wav *.ogg *.oga *.opus *.flac *.mp3)",
    "播放失败": "Playback Failed",
    "正在播放：/%1；日志：%2": "Playing: /%1; log: %2",
    "快速播放失败": "Quick Playback Failed",
    "正在重放：/%1/%2": "Replaying: /%1/%2",
    "上传代理启动失败": "Failed to Start Upload Proxy",
    "上传代理已启动（PID %1）": "Upload proxy started (PID %1)",
    "启动失败": "Startup Failed",
    "接收已启动；录音与日志：%1": "Receiver started; recording and logs: %1",
    "接收已启动；SatNOGS 上传已启用；录音与日志：%1": "Receiver started; SatNOGS upload enabled; recording and logs: %1",
    "系统默认输入设备": "System Default Input Device",
    "选择上传卫星": "Select Upload Satellite",
    "本次遥测上传目标：": "Telemetry upload target for this session:",
    "资料不完整": "Incomplete Information",
    "请填写呼号或昵称。": "Enter a callsign.",
    "保存失败": "Save Failed",
    "无法写入：\n%1": "Unable to write:\n%1",
    "配置文件提交失败。": "Failed to commit the configuration file.",
    "设置已保存": "Settings saved",
    "阿斯图系列卫星启动失败": "Failed to Start the ASRTU Series Satellite Suite",
    "阿斯图系列卫星跟踪与多普勒": "ASRTU Series Satellite Tracking and Doppler",
    "本地缓存": "local cache",
    "已载入本地 TLE 缓存，正在在线更新…": "Local TLE cache loaded; updating online…",
    "实时跟踪数据": "Live Tracking Data",
    "等待 TLE 数据": "Waiting for TLE data",
    "方位角": "Azimuth",
    "仰角": "Elevation",
    "距离": "Range",
    "多普勒": "Doppler",
    "接收频率": "Receive Frequency",
    "TLE 历元": "TLE Epoch",
    "卫星与频率": "Satellite and Frequency",
    "卫星": "Satellite",
    "频率预设": "Frequency Preset",
    "标称下行": "Nominal Downlink",
    "TLE 来源（每行一个，全部下载并合并）": "TLE Sources (one per line; all are downloaded and merged)",
    "等待更新": "Waiting for update",
    "立即更新 TLE": "Update TLE Now",
    "打开星历目录": "Open Ephemeris Directory",
    "地面站：%1°, %2°，%3 m": "Ground station: %1°, %2°, %3 m",
    "正在下载：%1": "Downloading: %1",
    "在线合并": "online merge",
    "所有 TLE 来源均下载失败": "All TLE sources failed to download",
    "在线更新失败，继续使用本地合并文件": "Online update failed; continuing with the local merged file",
    "已下载 %1/%2 个来源，合并 %3 颗卫星%4：all_sources.tle": "Downloaded %1/%2 sources and merged %3 satellites%4: all_sources.tle",
    "并保存": " and saved",
    "，但保存失败": ", but saving failed",
    "自定义": "Custom",
    "SGP4 计算失败": "SGP4 calculation failed",
    "阿斯图系列卫星接收解码": "ASRTU Series Satellite Receiver and Decoder",
}


tree = ET.parse(TS)
missing = []
for message in tree.findall(".//message"):
    source = message.findtext("source", default="")
    translation = message.find("translation")
    if source not in TRANSLATIONS:
        missing.append(source)
        continue
    translation.attrib.pop("type", None)
    translation.text = TRANSLATIONS[source]

if missing:
    raise SystemExit("Missing translations: " + repr(missing))

if hasattr(ET, "indent"):
    ET.indent(tree, space="    ")
tree.write(TS, encoding="utf-8", xml_declaration=True)
